apiVersion: v1
kind: Service
metadata:
  name: donation-service
  namespace: solidary-tech
  labels:
    project: solidary-tech
    environment: production
    costcenter: ngo-core
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: donation-service