apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-flag-service
  name: app-flag-service
  namespace: flag-service
spec:
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      app: app-flag-service
  template:
    metadata:
      labels:
        app: app-flag-service
    spec:
      initContainers:

