apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-analytics-service
  name: app-analytics-service
  namespace: analytics-service
spec:
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      app: app-analytics-service
  template:
    metadata:
      labels:
        app: app-analytics-service
    spec:
      containers:
        - name: app-analytics-service
          image: 396368123600.dkr.ecr.us-east-1.amazonaws.com/togglemaster_analytics-service:30fa2e6049e8a4b925dc7656c6649a27c5c55063
          imagePullPolicy: Always
          ports:
            - containerPort: 8005
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8005
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8005
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:4318"
            - name: OTEL_SERVICE_NAME
              value: "analytics-service"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.namespace=togglemaster"
          envFrom:
            - secretRef:
                name: analytics-db-secret
            - secretRef:
                name: analytics-db-secret-host  
