apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: volunteer-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/gabriel-cupertino/tech-challenge-gitops.git'
    targetRevision: main
    path: volunteer-service
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: solidary-tech
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true