apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-targeting-service
  name: app-targeting-service
  namespace: targeting-service
spec:
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      app: app-targeting-service
  template:
    metadata:
      labels:
        app: app-targeting-service
    spec:
      containers:
      - name: app-targeting-service
        image: 396368123600.dkr.ecr.us-east-1.amazonaws.com/togglemaster_targeting-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8003
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_HOST
          value: "postgres-targeting-service"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "targeting"
        - name: AUTH_SERVICE_URL
          value: "http://app-auth-service.auth-service.svc.cluster.local:8000" # Ajustado para bater na porta 8000 do SVC que vimos no kubectl get svc -A
---
apiVersion: v1
kind: Service
metadata:
  name: app-targeting-service
  namespace: targeting-service
  labels:
    app: app-targeting-service
spec:
  type: ClusterIP
  ports:
  - port: 8003
    targetPort: 8003
    protocol: TCP
  selector:
    app: app-targeting-service