apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-targeting-service
  name: app-targeting-service
  namespace: targeting-service
spec:
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      app: app-targeting-service
  template:
    metadata:
      labels:
        app: app-targeting-service
    spec:
      containers:
      - name: app-targeting-service
        image: 396368123600.dkr.ecr.us-east-1.amazonaws.com/togglemaster_targeting-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8003
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_HOST
          value: "postgres-targeting-service" # Ajuste se o host do seu postgres no cluster for diferente
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "targeting"
        - name: AUTH_SERVICE_URL
          value: "http://app-auth-service.auth-service.svc.cluster.local:8001" # URL interna do seu auth-service